name: ninjitsi

services:
  web:
    build:
      context: .
    environment:
      JITSI_URL: ${JITSI_URL:-http://localhost:8000}
    ports:
      - "${NINJITSI_PORT:-3000}:80"
    restart: unless-stopped
    volumes:
      - ninjitsi-data:/data

volumes:
  ninjitsi-data:
